image: maven:3.8.4-openjdk-17  # Imagen de Maven y Java que usa GitLab para el pipeline

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Compilando el proyecto..."
    - mvn clean compile

test:
  stage: test
  script:
    - echo "Ejecutando pruebas..."
    - mvn test

deploy:
  stage: deploy
  script:
    - echo "Desplegando el proyecto..."
    - mvn package
  only:
    - main
