name: Trigger GitLab CI/CD

on:
  push:
    branches:
      - main
      - develop  # Agregamos develop aquí

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Extrae el nombre de la rama de GITHUB_REF
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Disparando pipeline en GitLab para la rama $BRANCH"
          curl -X POST \
            -F token=$GITLAB_TOKEN \
            -F ref=$BRANCH \
            https://gitlab.com/api/v4/projects/63134381/trigger/pipeline
